// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.mattermost.plugin-wrapper-demo",
    "name": "Wrapper Demo",
    "description": "Illustrate how to inject CSS to wrap the Mattermost application absolutely positioned divs.",
    "version": "0.1.0",
    "min_server_version": "5.12.0",
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
